# Generated by Django 5.0.6 on 2024-06-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
