# Generated by Django 5.0.6 on 2024-06-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
