# Generated by Django 5.0.6 on 2024-06-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='isSuccessful',
            field=models.BooleanField(default=False),
        ),
    ]
