# Generated by Django 5.0.6 on 2024-06-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_order_customer_order_issuccessful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isSuccessful',
        ),
    ]
